#!/usr/bin/env python3
# -*- coding:utf-8 -*-
#
# This application is used to configure an AutoBuddy appliance
# 
# Copyright (c) 2015 François Wautier
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies
# or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR 
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
import subprocess,os,json,sys,glob,pwd

BUDDYLOCATION="/".join(os.path.realpath(__file__).split("/")[:-2])
currentowner=os.stat(BUDDYLOCATION)
username=pwd.getpwuid(currentowner.st_uid)[0]
sys.path.append(BUDDYLOCATION+"/Buddylib")

from collections import defaultdict
from getpass import getpass
import buddylib as bl
from urllib.request import urlopen

debug=False
lobtdevs=["hci0","hci1","hci2","hci3"]

def passgen():
    from random import shuffle,randrange
    lolet=list("0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ-_*.?")
    for i in range(5):
        shuffle(lolet)
    lolet *= 100
    for i in range(20):
        shuffle(lolet)
    startidx=randrange(len(lolet)-16)
    return "".join(lolet[startidx:startidx+16])

def keygen():
    from random import shuffle,randrange
    lolet=list("0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ`~!@#$%^&*()_+-|\[{]}?/.,<:;")
    for i in range(5):
        shuffle(lolet)
    lolet *= 1000
    for i in range(20):
        shuffle(lolet)
    startidx=randrange(len(lolet)-32)
    return "".join(lolet[startidx:startidx+32])


#This is basically a linear walk-through the needed settings...
mylocation={"timezone":"Europe/Paris","lat":48.8584,"lon":2.2945,"countryCode":"FR","regionName":"Paris","city":"Paris"}
try:
    mylocation=json.loads(urlopen("http://ip-api.com/json").read().decode())
except:
    pass
remindmeattheend=""
import os
user = os.getenv("SUDO_USER")
if user is None:
    iamsuper = False
else:
    iamsuper = True
    
os.system('clear')
print("\n\nWelcome to AutoBuddy configuration tool.")
if iamsuper:
    print ("It looks like you are running with root priviledges. Good!")
    print ("Be forwarned though, we will be setting your time zone, install some needed")
    print ("packages and will access PostgreSQL by masquerading as user 'postgres'.")
    print ("If you do not want this, or if you think it won't work, get out now and run")
    print ("this config tool as an unpriviledged users.")
else:
    print ("It looks like you are running without root priviledges. This means that")
    print ("there will be a number of tasks we will not be able to perform. What we")
    print ("will do is tell you what you  need to do when this config tool is done")
    print ("for AutoBuddy to work smoothly. We will also ask you for the user name and")
    print ("password of a PostgreSQL superusers so we can setup the database")
 

gotit=False
while not gotit:
    choice = input("\n  Do you want to continue? [yes/no] : ")
    if choice.strip().lower() in ["n", "no", "no way","hell no"]:
        try:
            print ("\nAt your request, we will now perform ritual 切腹. さよなら")
        except:
            print ("\nAt your request, we will now perform ritual seppuku. Sayonara.")
            print ("        BTW, you really should use UTF-8.")
        sys.exit(0)
    elif choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
        gotit=True
    else:
        print ("\nJust answer Yes or No. How difficult is that?")

os.system('clear')
#Starting with time zone
if not iamsuper or not os.path.isfile(BUDDYLOCATION+"/.autobuddyneedconfig"):
    print ("\nWe believe your timezone is %s"%mylocation["timezone"])
    print ("If somehow we got that wrong, please be sure to update your location")
    print ("once you have access to AutoBuddy. In Menu > Configure > System Configuration")
    remindmeattheend+=" Check you location in Menu > Configure > System Configuration\n\n"
else:
    print("\nLet's start by updating your time zone.")
    gotit=False
    while not gotit:
        print ("\n\nOK, me think your time zone is %s"%mylocation["timezone"])
        for x in ["Yes","No"]:
            print("\t %s"%x)
        print()
        choice = input(" Your choice: ")
        try:
            if choice.strip().lower() in ['y',"yes","yay","sure","yep","affirmative"]:
                gotit=True
                choice=mylocation["timezone"]
            elif choice.strip().lower() in ['n','no','nope','nay','negative','wrong']:
                gotit=True
                choice=""
            else:
                raise Exception
        except:
            os.system('clear')
            print ("\n\nInput not recognized. Please pay attention.")
            
    if not choice:    
        print ("\n\nOoops, I got it wrong, my bad! Let's try another way.")
        lotz=subprocess.check_output(["timedatectl", "--no-pager","list-timezones"]).decode()
        tzlist=defaultdict(list)
        for rawzone in lotz.split("\n"):
            if not rawzone:
                continue
            zone=rawzone.split("/")
            if len(zone) == 1:
                tzlist[zone[0]]=None
            else:
                tzlist[zone[0]].append("/".join(zone[1:]))        
        lotopz=list(tzlist.keys())
        lotopz.sort()
        os.system('clear')
        gotit=False
        mode="init"
        weredone=False
        while not weredone:
            if mode=="init":
                while not gotit:
                    idx=0
                    print ("\n\nPlease do select the number corresponding to your time zone")
                    for x in lotopz:
                        print ("   %d\t %s"%(idx,x))
                        idx+=1
                    print()
                    choice = input(" Your choice: ")
                    try:
                        choice=int(choice)
                        if choice < 0 or choice >= len(lotopz):
                            raise Exception
                        gotit=True
                    except:
                        os.system('clear')
                        print ("\n\nInput not recognized. Please pay attention.")
                        
            mode="sub"
            os.system('clear')
            topzone=lotopz[choice]    
            if tzlist[topzone]:
                #Find more
                sidx=0
                maxidx=10
                gotit=False
                while not gotit:
                    print ("\n\n\nPlease do select the number corresponding to your time zone")
                    idx=0
                    while idx< min(maxidx,len(tzlist[topzone])-sidx):
                        print ("   %d\t %s/%s"%(idx,topzone,tzlist[topzone][sidx+idx]))
                        idx+=1
                    print ("\n\nUse 'b' to go back to the previous screen. 'n' to go to the next one.\n")
                    choice = input(" Your choice: ")
                    try:
                        if choice.strip().lower()=='b':
                            if sidx == 0:
                                mode="init"
                                os.system('clear')
                                break
                            else:
                                sidx-=maxidx
                                os.system('clear')
                        elif choice.strip().lower()=='n':
                            if sidx+maxidx < len(tzlist[topzone]):
                                sidx+=maxidx
                            os.system('clear')
                        else:
                            choice=int(choice)
                            if choice < 0 or choice >= min(maxidx,len(tzlist[topzone])-sidx):
                                raise Exception
                            gotit=True
                            weredone=True
                            choice=topzone+"/"+tzlist[topzone][choice+sidx]
                    except:
                        os.system('clear')
                        print ("Input not recognized. Please pay attention.")
                            
                        
    if debug:
        print ("We got %s"%choice)
    else:
        lotz=subprocess.check_output(["timedatectl", "set-timezone",choice])    

    os.system('clear')
    print("\n\n\n\n Time zone was set to %s"%choice)
 
if not os.path.isfile(BUDDYLOCATION+"/.autobuddyneedconfig"):
    choice = input(" Press '<enter>' to continue")
    os.system('clear')

    if not iamsuper:
        print ("\nAutoBuddy requires a number of packages to be installed in order to work.")
        print ("On a Debian/Ubuntu type of distribution, the following 2 command should be run:\n")
        print("\tsudo apt -y install postgresql python3-sqlalchemy python3-crypto python3-psycopg2 python3-aiohttp \\\n\t\t\t\tpython3-ephem python3-dateutil python3-crontab python3-bitstring python3-pip")
        print("\tsudo pip3 install aiolifx aioarping aiobtname\n")
        remindmeattheend+="\nMake sure the needed packages are installed:\n\n"
        remindmeattheend+="\tsudo apt -y install postgresql python3-sqlalchemy python3-crypto python3-psycopg2 python3-aiohttp \\\n\t\t\t\tpython3-ephem python3-dateutil python3-crontab python3-bitstring python3-pip"
        remindmeattheend+="\n\tsudo pip3 install aiolifx aioarping aiobtname\n\n"
    else:
        print("\n\n\n\nNow we shall install the packages we need... You had better be on Debian with apt for this to work")
        choice = input(" Press '<enter>' to proceed")
        try:
            subprocess.run(["apt","-y","install","postgresql","python3-sqlalchemy","python3-crypto","python3-psycopg2","python3-aiohttp","python3-ephem","python3-dateutil","python3-crontab","python3-bitstring"])
            subprocess.run(["pip3","install","aiobtname","aioarping","aiolifx"])
            print("Allright, it looks like we are done.")
        except:
            print("Something wrong just happened....Let's continue anyway. Danger is my middle name")
        choice = input(" Press '<enter>' to continue")
        os.system('clear')
    
print("\n\n\n\nNow we shall install all the bits needed and packaged in a tar file.")
choice = input(" Press '<enter>' to proceed")
try:
    subprocess.run(["tar","xvfj",BUDDYLOCATION+"/alltherest.tar.bz2","-C", BUDDYLOCATION])
    print("Allright, it looks like we are done.")
except:
    print("Something wrong just happened....Let's continue anyway. Danger is my middle name")

choice = input(" Press '<enter>' to continue")
os.system('clear')
if os.path.isfile(BUDDYLOCATION+"/.autobuddyneedconfig"):
    weredone=False
    newpasswd=""
    while not weredone:
        print ("\n\n\n We will now set a new password for the default user 'autobuddy'.\n\n")
        passwd = getpass(" Password: ")
        confirm = getpass(" Confirm Password: ")
        if passwd == confirm :
            weredone = True
            newpasswd=passwd
        else:
            os.system('clear')
            print ("\n\n The passwords did not match.")

    if debug:
        print ("New password is %d"%newpasswd)
    else:
        chpass=subprocess.Popen(["chpasswd"], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
        d_out=chpass.communicate(input="autobuddy:%s"%newpasswd)[0]
    
    os.unlink(BUDDYLOCATION+"/.autobuddyneedconfig")
    os.system('clear')
    
    print ("\n\n\n\n Password was set.\n\n")
    choice = input(" Press '<enter>' to continue")


if not iamsuper:
    psqldbok=False
    psqluser=None
    print ("\nWe now need to setup PostgreSQL, create a database and 2 users.")
    print ("If you want I can perform these operation but I need a username and password with adequate permissions.")
    print ("\nWould you like to setup the database by providing a user name and password?")
    gotit=False
    while not gotit:
        choice = input("\n Your choice? [yes/no] : ")
        if choice.strip().lower() in ["n", "no", "no way","hell no"]:
            gotit=True
            print("Ok, we'll tell you what needs to be done.")      
        elif choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
            gotit=True
            psqldbok=True
            psqluser=input("\n Please input the username : ")
            psqlpasswd=input("\n Please input the password : ")
            print("Ok, we'll use user %s with password %s"%(psqluser,psqlpasswd))
            my_env = os.environ.copy()
            my_env["PGUSER"] = psqluser   
            my_env["PGPASSWORD"] = psqlpasswd     
        else:
            print ("Just answer Yes or No. How difficult is that?")    
else:
    psqldbok=True
    psqluser=None
    
       

createdb="CREATE DATABASE autobuddy ENCODING 'UTF8';"
pgreadonlyuser="""
CREATE USER readbuddy WITH ENCRYPTED PASSWORD '%s';
GRANT CONNECT ON DATABASE autobuddy TO readbuddy;
GRANT USAGE ON SCHEMA public TO readbuddy;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readbuddy;
GRANT SELECT ON ALL TABLES IN SCHEMA public to readbuddy;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO readbuddy;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readbuddy;
"""
pgmainuser="""
CREATE USER autobuddy WITH ENCRYPTED PASSWORD '%s';
GRANT ALL PRIVILEGES ON DATABASE autobuddy TO autobuddy;
"""
xx=input("\n Press <enter> to continue...")
os.system('clear')
weredone=False
newpasswd=""
while not weredone:
    print ("\n\n\n We will now define a password for the \"autobuddy\"  user in PostgreSQL.\n This user has all access to the \"autobuddy\" database.\n\n")
    print (" If you leave the password empty, I will generate the password automatically.\n\n")
    passwd = getpass(" Password: ")
    if passwd:
        confirm = getpass(" Confirm Password: ")
        if passwd == confirm :
            weredone = True
            dbpasswd=passwd
        else:
            os.system('clear')
            print ("\n\n The passwords did not match.")
    else:
        dbpasswd=passgen()
        weredone = True
    
    
weredone=False
newpasswd=""
while not weredone:
    print ("\n\n\n We will now define a password for the \"readbuddy\"  user in PostgreSQL.\n This user has read-only access to the \"autobuddy\" database.\n\n")
    print (" If you leave the password empty, I will generate the password automatically.\n\n")
    passwd = getpass(" Password: ")
    if passwd:
        confirm = getpass(" Confirm Password: ")
        if passwd == confirm :
            weredone = True
            ropasswd=passwd
        else:
            os.system('clear')
            print ("\n\n The passwords did not match.")
    else:
        ropasswd=passgen()
        weredone = True
          
if psqldbok:
    newconfig=createdb+pgmainuser%dbpasswd + pgreadonlyuser%ropasswd
    if debug:
        print ("New passwords are {} and {}.".format(dbpasswd,ropasswd))
    else:
        if psqluser:
            sqlproc=subprocess.Popen(["/usr/bin/psql"], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True,env=my_env)
        else:
            sqlproc=subprocess.Popen(["sudo", "-u", "postgres", "/usr/bin/psql"], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
        d_out=sqlproc.communicate(input=newconfig)
        
    os.system('clear')
    print("\n\n\n\n Database was created, so were users and passwords were set.\n\n")
    choice = input(" Press '<enter>' to continue")
else:
    remindmeattheend+="You need to create database and users with:\n"
    remindmeattheend+=createdb+"\n"
    remindmeattheend+=pgmainuser%dbpasswd + pgreadonlyuser%ropasswd
    
os.system('clear')
print ("\n\n\n\n I need to know the name of the top zone.\n\n")
choice = input(" Top Zone Name [Home]: ")
if not choice:
    topzone="Home"
else:
    topzone=choice
 
os.system('clear')

dolifx=False
doflic=False
dovoice=False
dopresence=False
dopresencelan=False
dopresencebt=False

print("Finaly, we need to know which optional modules you want to run.")
print("\n\nLifxBuddy allows you to control your Lifx LED bulbs.")

choice = input("\n  Do you want to run it? [yes/NO] : ")
if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
    dolifx=True

print("\n\nPresenceBuddy allows you to detect people's presence by monitoring their devices")
print("(like smartphone) over LAN and/or over Bluetooth.")
choice = input("\n  Do you want to run it? [yes/NO] : ")
if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
    dopresence=True
    
if dopresence:
    choice = input("\n  Do you want to use ARPing over the LAN for presence (not recommended)? [yes/NO] : ")
    if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
        dopresencelan=True
    else:
        dopresencelan=False
    choice = input("\n  Do you want to use Bluetooth for  presence (recommended)? [yes/NO] : ")
    if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
        dopresencebt=lobtdevs[0]
        lobtdevs=lobtdevs[1:]
    else:
        dopresencelan=False

print("\n\nFlicBuddy allows you to receive click event from your flic buttons.")

choice = input("\n  Do you want to run it? [yes/NO] : ")
if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
    doflic=lobtdevs[0]
    lobtdevs=lobtdevs[1:]

print("\n\nVoiceBuddy allows you configure voice commands.")

choice = input("\n  Do you want to run it? [yes/NO] : ")
if choice.strip().lower() in ["y", "ye", "yes","let's do this","ok"]:
    dovoice=True
    
voicedev="default"
if dovoice:
    import alsaaudio
    gotit = False
    while not gotit:
        print (" Please select the audio device to use for listening.")
        lastdev = 0
        for dnb,dname in enumerate(alsaaudio.cards()):
            print ("   %d\t %s"%(dnb,dname))
            lastdev = dnb
        choice = input("Your choice: ")
        try:
            choice=int(choice)
            if choice >= 0  and choice <= lastdev:
                gotit = True
                voicedev = "plughw:%d,0"%choice
            else:     
                os.system('clear')
                print ("\nInput must be an integer between 0 and %d!"%lastdev)
        except:
            os.system('clear')
            print ("\nInput must be an integer!")

print("\nYou have decided:")
if dolifx:
    print("\tto run LifxBuddy")
else:
    print("\tnot to run LifxBuddy")

if dopresence and (dopresencebt or dopresencelan):
    if dopresencebt and dopresencelan:
        print("\tto run PresenceBuddy over LAN and Bluetooth")
    elif dopresencebt:
        print("\tto run PresenceBuddy over Bluetooth")
    else:
        print("\tto run PresenceBuddy over LAN")
else:    
    print("\tnot to run PresenceBuddy")
    
if doflic:
    print("\tto run FlicBuddy")
else:
    print("\tnot to run FlicBuddy")
   
if dovoice:
    print("\tto run VoiceBuddy with {}".format(voicedev))
else:
    print("\tnot to run VoiceBuddy")
    

if doflic and dopresencebt:
    print("\nNote: Given you are using both BuddyFlic and using Bluetooth for presence, you must have 2 Bluetooth adapters.\n")
print ("\n\n\n\n Thank you, I will now proceed and finalize the configuration.\n\n")
choice = input(" Press '<enter>' to continue")
   
certdir=BUDDYLOCATION+"/.tls"
try:
    os.mkdir(certdir,mode=0o700)
except FileExistsError:
    pass

os.chown(certdir,currentowner.st_uid,currentowner.st_gid)

try:
    os.mkdir(BUDDYLOCATION+"/.buddyconfig",mode=0o700)
except FileExistsError:
    pass

os.chown(BUDDYLOCATION+"/.buddyconfig",currentowner.st_uid,currentowner.st_gid)

try:
    os.mkdir(BUDDYLOCATION+"/.run",mode=0o700)
except FileExistsError:
    pass

os.chown(BUDDYLOCATION+"/.run",currentowner.st_uid,currentowner.st_gid)


subj="/C=%s/ST=%s/L=%s/O=AutoBuddy Security/OU=Home Security/CN=autobuddy.local"%(mylocation["countryCode"],mylocation["regionName"],mylocation["city"])

subprocess.run(["openssl", "req", "-x509", "-nodes", "-days", "7300", "-newkey", "rsa:2048", "-keyout", BUDDYLOCATION+"/.tls/autobuddy.key", "-out",
                BUDDYLOCATION+"/.tls/autobuddy.crt", "-subj", subj])
print("Self-signed certificate was created")

os.chown(BUDDYLOCATION+"/.tls/autobuddy.key",currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/.tls/autobuddy.key",0o600)
os.chown(BUDDYLOCATION+"/.tls/autobuddy.crt",currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/.tls/autobuddy.crt",0o600)

credential=passgen()
print ("Credential will be {}.".format(credential))
mycfg={}
mycfg["zone"]=topzone
mycfg["database"] = {"db": "autobuddy", "host": "localhost", "driver": "postgres", "user": "autobuddy","password":dbpasswd}
mycfg["dbronly"] = {"user": "readbuddy","password":ropasswd}
mycfg["type"] = "control"
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()

controlkey=mycfg["buddykey"]

fn=BUDDYLOCATION+"/.buddyconfig/config.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/ControlBuddy/ControlBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
"""
mycmd+=BUDDYLOCATION+"/ControlBuddy/ControlBuddy -c "+fn
mycmd+="\nsleep 10\ndone\n"
fn=BUDDYLOCATION+"/.run/01-control"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
bustartcmd="#!/bin/bash\n    tmux new-session -s AutoBuddy -n ControlBuddy -d "+fn

print ("Still working!")

mycfg={}
mycfg["tls"]=certdir
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()
mycfg["application"] = BUDDYLOCATION+"/WebBuddy/buddyctrl.html"
mycfg["host"] = "*"
mycfg["port"] = 8090
mycfg["type"] = "guibridge"
mycfg["broker"] = "localhost"
mycfg["credential"] = credential
socketkey = mycfg["buddykey"]

fn=BUDDYLOCATION+"/.buddyconfig/websocket.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/SocketBuddy/SocketBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 12
"""
mycmd+=BUDDYLOCATION+"/SocketBuddy/SocketBuddy -c "+fn
mycmd+="\ndone\n"
fn=BUDDYLOCATION+"/.run/99-socket"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n SocketBuddy "+fn

print ("Still working!")

mycfg={}
mycfg["host"]= "localhost"
mycfg["type"] = "light"
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()

fn=BUDDYLOCATION+"/.buddyconfig/lifx.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/LifxBuddy/LifxBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 10
"""
mycmd+=BUDDYLOCATION+"/LifxBuddy/LifxBuddy -c "+fn
mycmd+="\nsleep 2\ndone\n"
fn=BUDDYLOCATION+"/.run/30-lifx"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
if dolifx:
    bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n LifxBuddy "+fn
else:
    bustartcmd+="\n    #tmux new-window -t AutoBuddy -d -n LifxBuddy "+fn

print ("Patience!")


mycfg={}
mycfg["host"]= "localhost"
mycfg["type"] = "switch"
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()
mycfg["flichost"] = "localhost"
mycfg["flicpath"] = BUDDYLOCATION + "/FlicBuddy/flicd/"
mycfg["btiface"] = doflic or "hci0"

fn=BUDDYLOCATION+"/.buddyconfig/flic.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/FlicBuddy/FlicBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 10
"""
mycmd+=BUDDYLOCATION+"/FlicBuddy/FlicBuddy -c "+fn
mycmd+="\n    sleep 2\ndone\n"
fn=BUDDYLOCATION+"/.run/30-flic"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
if doflic:
    bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n FlicBuddy "+fn
else:
    bustartcmd+="\n    #tmux new-window -t AutoBuddy -d -n FlicBuddy "+fn

print ("Just a little longer!")

mycfg={}
mycfg["host"]= "localhost"
mycfg["type"] = "action"
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()
actionkey=mycfg["buddykey"]
fn=BUDDYLOCATION+"/.buddyconfig/action.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/ActionBuddy/ActionBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 10
"""
mycmd+=BUDDYLOCATION+"/ActionBuddy/ActionBuddy -c "+fn
mycmd+="\n    sleep 2\ndone\n"
fn=BUDDYLOCATION+"/.run/50-action"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n ActionBuddy "+fn

mycfg={}
mycfg["host"]= "localhost"
mycfg["type"] = "presence"
mycfg["subtype"] = "mac"
if dopresence and dopresencelan:
    mycfg["lan"] = "true"
else:
    mycfg["lan"] = "false"
if dopresencebt:
    mycfg["btdev"] = int(dopresencebt[-1])
elif not dopresence:
    mycfg["btdev"] = 0
                
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()
actionkey=mycfg["buddykey"]
fn=BUDDYLOCATION+"/.buddyconfig/presence.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/PresenceBuddy/PresenceBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 10
"""
mycmd+=BUDDYLOCATION+"/PresenceBuddy/PresenceBuddy -c "+fn
mycmd+="\n    sleep 2\ndone\n"
fn=BUDDYLOCATION+"/.run/50-presence"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
if dopresence:
    bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n PresenceBuddy "+fn
else:
    bustartcmd+="\n    #tmux new-window -t AutoBuddy -d -n PresenceBuddy "+fn

mycfg={}
mycfg["host"]= "localhost"
mycfg["type"] = "voice"
mycfg["subtype"] = "main"

mycfg["modeldir"] = "/usr/share/pocketsphinx/model/en-us/en-us"
mycfg["voicepath"] = BUDDYLOCATION+"/VoiceBuddy/"
mycfg["mic"] = voicedev
        
mycfg["credential"] = credential
mycfg["ssl"]=certdir
mycfg["buddykey"] = keygen()
actionkey=mycfg["buddykey"]
fn=BUDDYLOCATION+"/.buddyconfig/voice.cfg"
with open(fn,"w") as cfile:
    json.dump(mycfg,cfile)
os.chmod(fn,0o600)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(BUDDYLOCATION+"/VoiceBuddy/VoiceBuddy",0o775)
mycmd="""#!/bin/bash
export PYTHONPATH="""
mycmd+=BUDDYLOCATION+"/Buddylib"
mycmd+="""
while [ 1 ]; do
sleep 10
"""
mycmd+=BUDDYLOCATION+"/VoiceBuddy/VoiceBuddy -c "+fn
mycmd+="\n    sleep 2\ndone\n"
fn=BUDDYLOCATION+"/.run/50-voice"
with open(fn,"w") as cfile:
    cfile.write(mycmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)
if dovoice:
    bustartcmd+="\n    tmux new-window -t AutoBuddy -d -n VoiceBuddy "+fn
else:
    bustartcmd+="\n    #tmux new-window -t AutoBuddy -d -n VoiceBuddy "+fn





fn=BUDDYLOCATION+"/.start-autobuddy"
with open(fn,"w") as cfile:
    cfile.write(bustartcmd)
os.chown(fn,currentowner.st_uid,currentowner.st_gid)
os.chmod(fn,0o750)


mycfg["database"] = {"db": "autobuddy", "host": "localhost", "driver": "postgres", "user": "autobuddy","password":dbpasswd}

bdb = mycfg["database"]["driver"] + "://"
if "user" in mycfg["database"] and mycfg["database"]["user"]:
    bdb += mycfg["database"]["user"] + ":" + mycfg["database"]["password"] + "@"
bdb += mycfg["database"]["host"]

if "port" in mycfg["database"] and mycfg["database"]["port"]:
    bdb += ":"+ str(mycfg["database"]["port"])
bdb += "/" + mycfg["database"]["db"]

print ("Almost there!")
if psqldbok:
    #print "Connecting with",bdb
    sess=bl.getSession(bdb)
    bl.initialize(sess)
    nzone=bl.Zone()
    nzone.name="zone-BuddyRoot"
    nzone.nickname=topzone
    sess.add(nzone)
    nprop=bl.BuddyProperty()
    nprop.entity="guibridge"
    nprop.name="users"
    nprop.values=bl.encrypt({"admin":["password","admin"]},socketkey)
    sess.add(nprop)
    nprop=bl.BuddyProperty()
    nprop.entity="System"
    nprop.name="configuration"
    nprop.values=bl.encrypt({"location":{"longitude":mylocation["lon"],"latitude":mylocation["lat"],"altitude":4}},controlkey)
    sess.add(nprop)
    nprop=bl.BuddyProperty()
    nprop.entity="action"
    nprop.name="rules"
    nprop.values=bl.encrypt({},actionkey)
    sess.add(nprop)
    nprop=bl.BuddyProperty()
    nprop.entity="action"
    nprop.name="state variable"
    nprop.values=bl.encrypt({},actionkey)
    sess.add(nprop)
    sess.commit()


#Bloddy grant select!
newconfig="""GRANT SELECT ON TABLE device TO readbuddy;
GRANT SELECT ON TABLE zone TO readbuddy;
"""         
if psqldbok:
    if psqluser:
        sqlproc=subprocess.Popen(["/usr/bin/psql","autobuddy"], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True,env=my_env)
    else:
        chpass=subprocess.Popen(["sudo", "-u", "postgres", "/usr/bin/psql","autobuddy"], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
    d_out=chpass.communicate(input=newconfig)

if not iamsuper:
    remindmeattheend+="\nYou must permit access to bluetooth adapter with:\n"
    
for fname in glob.glob(BUDDYLOCATION + "/FlicBuddy/flicd/flicd.*") :
    if iamsuper:
        subprocess.run(["/sbin/setcap", "cap_net_admin=ep", fname])
        subprocess.run(["/sbin/setcap", "cap_net_bind_service=+ep", "/usr/bin/python3.5"])
        subprocess.run(["/sbin/setcap", "cap_net_raw=+ep", "/usr/bin/python3.5"])
    else:
        remindmeattheend+="\tsudo /sbin/setcap cap_net_admin=ep" + fname +"\n"
        remindmeattheend+="\tsudo /sbin/setcap 'cap_net_bind_service=+ep' /usr/bin/python3.5\n"
        remindmeattheend+="\tsudo /sbin/setcap 'cap_net_raw=+ep' /usr/bin/python3.5\n"

if not psqldbok:
    remindmeattheend+="\n\nAfter creating the database you will also need to run the python script to bootstrap that database:\n\n"
    remindmeattheend+="import sys\n"
    remindmeattheend+="sys.path.append(\"%s\")\n"%(BUDDYLOCATION+"/Buddylib")
    remindmeattheend+="import buddylib as bl\n"
    remindmeattheend+="sess=bl.getSession(\"%s\")\n"%bdb
    remindmeattheend+="bl.initialize(sess)\n"
    remindmeattheend+="nzone=bl.Zone()\n"
    remindmeattheend+="nzone.name=\"zone-BuddyRoot\"\n"
    remindmeattheend+="nzone.nickname=topzone\n"
    remindmeattheend+="sess.add(nzone)\n"
    remindmeattheend+="nprop=bl.BuddyProperty()\n"
    remindmeattheend+="nprop.entity=\"guibridge\"\n"
    remindmeattheend+="nprop.name=\"users\"\n"
    remindmeattheend+="nprop.values=bl.encrypt({\"admin\":[\"password\",\"admin\"]},\"%s\")\n"%socketkey
    remindmeattheend+="sess.add(nprop)\n"
    remindmeattheend+="nprop=bl.BuddyProperty()\n"
    remindmeattheend+="nprop.entity=\"System\"\n"
    remindmeattheend+="nprop.name=\"configuration\"\n"
    remindmeattheend+="nprop.values=bl.encrypt({\"location\":{\"longitude\":%.8f,\"latitude\":%.8f,\"altitude\":4}},\"%s\")\n"%(mylocation["lon"],mylocation["lat"],controlkey)
    remindmeattheend+="sess.add(nprop)\n"
    remindmeattheend+="nprop=bl.BuddyProperty()\n"
    remindmeattheend+="nprop.entity=\"action\"\n"
    remindmeattheend+="nprop.name=\"rules\"\n"
    remindmeattheend+="nprop.values=bl.encrypt({},\"%s\")\n"%actionkey
    remindmeattheend+="sess.add(nprop)\n"
    remindmeattheend+="nprop=bl.BuddyProperty()\n"
    remindmeattheend+="nprop.entity=\"action\"\n"
    remindmeattheend+="nprop.name=\"state variable\"\n"
    remindmeattheend+="nprop.values=bl.encrypt({},\"%s\")\n"%actionkey
    remindmeattheend+="sess.add(nprop)\n"
    remindmeattheend+="sess.commit()\n"
    remindmeattheend+="\n\n"
    
if not psqldbok:
    remindmeattheend+="\nAfter that, you need to connect to the database again and do:"
    remindmeattheend+="\n"+newconfig+"\n"
#Update in BuddyTools
for fn in os.listdir(BUDDYLOCATION+"/BuddyTools"):
    with open(BUDDYLOCATION+"/BuddyTools/"+fn, 'r') as file :
        filedata = file.read()
        # Replace the target string
        for val,newval in [("<AUTOBUDDYHOST/>",os.uname()[1]),
                        ("<AUTOBUDDYPORT/>","8745"),
                        ("<AUTOBUDDYCREDENTIAL/>",credential)]:
            filedata = filedata.replace(val, newval)
    
    with open(BUDDYLOCATION+"/BuddyTools/"+fn, 'w') as file :
        file.write(filedata)
try:
    from crontab import CronTab
    cron=CronTab(user=username)
    job  = cron.new(command=BUDDYLOCATION+"/.start-autobuddy")
    job.every_reboot()
    cron.write()
    print ("\n\n\n\n We are done.\n\n After reboot, point your browser to https://autobuddy.local:8090/.\n\n Login with username \"admin\" and password \"password\".")
    print ("\nIf you plan to connect remote buddies, you'll need enable remote access to PostgreSQL\nand use the credential {}".format(credential))
    #choice = input(" Press '<enter>' to reboot")
    #os.system("reboot")
except:
    print ("\n\n\n\n We are done. We are about to reboot but ...")
    print ("For some reason we were not able to schedule the start of the AutoBuddy system. In the terminal, please do:")
    print ("\n          (crontab -l 2>/dev/null; echo \"@reboot "+BUDDYLOCATION+"/.start-autobuddy\") | crontab -\n")
    print ("Cut and paste if possible. After that you should reboot with \"sudo reboot\"")
    print("\n\n After reboot, point your browser to https://autobuddy.local:8090/.\n\n Login with username \"admin\" and password \"password\".")

if remindmeattheend:
    print("\n\nHere is a reminder of what you still need to do before you can reboot:")
    print(remindmeattheend)